# Generated by Django 4.2.27 on 2026-03-03 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tamu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_standar', models.CharField(max_length=100, unique=True)),
                ('kata_kunci', models.TextField()),
            ],
            options={
                'verbose_name': 'Instansi',
                'verbose_name_plural': 'Daftar Instansi',
            },
        ),
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PIC',
                'verbose_name_plural': 'Daftar PIC',
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('divisi', models.CharField(max_length=50)),
                ('jabatan', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BukuTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_masuk', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Konfirmasi'), ('MASUK', 'Sedang Bertamu'), ('SELESAI', 'Selesai Bertamu'), ('KELUAR', 'Sudah Checkout')], default='MENUNGGU', max_length=20)),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('instansi', models.CharField(max_length=150, verbose_name='Nama Instansi')),
                ('no_hp', models.CharField(default='-', max_length=20, verbose_name='No Telfon/HP')),
                ('no_polisi', models.CharField(blank=True, max_length=20, null=True, verbose_name='No Polisi Kendaraan')),
                ('foto_ktp', models.ImageField(upload_to=tamu.models.rename_file_ktp, verbose_name='Foto KTP')),
                ('keperluan', models.TextField(verbose_name='Keperluan')),
                ('jumlah_tamu', models.PositiveBigIntegerField(default=1, verbose_name='Jumlah Orang')),
                ('sudah_janji', models.BooleanField(default=False, verbose_name='Sudah Janji?')),
                ('foto_wajah', models.ImageField(blank=True, null=True, upload_to=tamu.models.rename_file_selfie, verbose_name='Foto Wajah (Selfie)')),
                ('kategori_tamu', models.CharField(choices=[('rekan_bisnis', 'Lokal Rekan Bisnis'), ('pemerintahan', 'Pemerintahan'), ('akademisi', 'Akademisi'), ('overseas', 'Overseas Guests (Luar Negeri)')], default='rekan_bisnis', max_length=50, verbose_name='Kategori Tamu')),
                ('waktu_keluar', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bawa_barang', models.CharField(blank=True, max_length=200, null=True, verbose_name='Barang Bawaan')),
                ('jumlah_barang', models.IntegerField(default=0, verbose_name='Jumlah Barang')),
                ('pic_tuju', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tamu.pic')),
            ],
            options={
                'verbose_name_plural': 'Daftar Tamu',
                'ordering': ['-waktu_masuk'],
            },
        ),
    ]
