# Generated by Django 4.2.27 on 2026-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamu', '0002_logaktivitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='departemen',
            field=models.CharField(default='Umum', max_length=100),
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='no_hp',
            field=models.CharField(max_length=20, verbose_name='No Telfon/HP'),
        ),
    ]
