# Generated by Django 4.2.27 on 2026-04-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamu', '0003_pic_departemen_alter_bukutamu_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='departemen',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
