# Generated by Django 4.2.27 on 2026-04-22 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tamu', '0004_alter_pic_departemen'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaktivitas',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bukutamu',
            name='status',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu Konfirmasi'), ('MASUK', 'Sedang Bertamu'), ('SELESAI', 'Selesai Bertamu'), ('KELUAR', 'Sudah Checkout'), ('DITOLAK', 'Ditolak/Batal')], default='MENUNGGU', max_length=20),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logaktivitas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
